stages:
    - build

clang-3.9:
    stage: build
    script:
       - ./tools/ci/clang39.sh
    image: debian:unstable

gcc-6.1:
    stage: build
    script:
       - ./tools/ci/gcc61.sh
    image: debian:unstable

