stages:
    - build

clang-3.9:
    stage: build
    script:
       - ./tools/ci/clang39.sh
    image: debian:unstable

gcc-6:
    stage: build
    script:
       - ./tools/ci/gcc6.sh
    image: debian:unstable

