variables:
    GIT_SUBMODULE_STRATEGY: recursive
stages:
    - build
    - test
    - documentation

build:clang:
    stage: build
    script:
       - ./tools/ci/dependency.sh
       - ./tools/ci/clang.sh
    artifacts:
      untracked: true
    image: debian:unstable

build:gcc:
    stage: build
    script:
       - ./tools/ci/dependency.sh
       - ./tools/ci/gcc.sh
    artifacts:
      untracked: true
    image: debian:unstable

test:clang:
    stage: test
    dependencies:
      - build:clang
    script:
       - ./tools/ci/dependency.sh
       - ./tools/ci/simpleTest.sh
    image: debian:unstable


test:gcc:
    stage: test
    dependencies:
      - build:gcc
    script:
       - ./tools/ci/dependency.sh
       - ./tools/ci/test.sh
    artifacts:
      paths:
        - build/out-coverage
    image: debian:unstable

documentation:
     stage: documentation
     script:
       - ./tools/ci/doxygen.sh
     artifacts:
       paths:
        - docs/html
     when: always
