variables:
    GIT_SUBMODULE_STRATEGY: recursive
stages:
    - build

build:clang-3.9:
    stage: build
    script:
       - ./tools/ci/clang39.sh
       - ./tools/ci/test.sh
    artifacts:
      paths:
        - build/out-coverage
    image: debian:unstable

build:gcc-6:
    stage: build
    script:
       - ./tools/ci/gcc6.sh
       - ./tools/ci/test.sh
    artifacts:
      paths:
        - build/out-coverage
    image: debian:unstable

