variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
  - build
  - documentation

build:clang:
  stage: build
  script:
    - ./tools/ci/dependency.sh
    - ./tools/ci/clang.sh
    - ./tools/ci/simpleTest.sh
  artifacts:
    reports:
      junit: build/report.xml
  image: debian:unstable

build:gcc:
  stage: build
  script:
    - ./tools/ci/dependency.sh
    - ./tools/ci/gcc.sh
    - ./tools/ci/test.sh
  artifacts:
    paths:
      - build/out-coverage
    reports:
      junit: build/report.xml
  image: debian:unstable

documentation:
  stage: documentation
  script:
    - ./tools/ci/dependency.sh
    - ./tools/ci/doxygen.sh
  artifacts:
    paths:
      - build/docs/html
  when: always
  image: debian:unstable
