variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
  - build
  - documentation

build:clang:
  stage: build
  script:
    - ./tools/ci/clang.sh
    - ./tools/ci/simpleTest.sh
  artifacts:
    reports:
      junit: build/report.xml
  image: monwarez/simple3dengine:latest

build:gcc:
  stage: build
  script:
    - ./tools/ci/gcc.sh
    - ./tools/ci/test.sh
  artifacts:
    paths:
      - build/meson-logs/coveragereport
    reports:
      junit: build/report.xml
  image: monwarez/simple3dengine:latest

documentation:
  stage: documentation
  script:
    - ./tools/ci/doxygen.sh
  artifacts:
    paths:
      - build/docs/html
  when: always
  image: monwarez/simple3dengine:latest
