variables:
    GIT_SUBMODULE_STRATEGY: recursive
stages:
    - build
    - test
    - documentation

build:clang-3.9:
    stage: build
    script:
       - ./tools/ci/clang39.sh
    artifacts:
      untracked: true
    image: debian:unstable

build:gcc-6:
    stage: build
    script:
       - ./tools/ci/gcc6.sh
    artifacts:
      untracked: true
    image: debian:unstable

test:clang-3.9:
    stage: test
    dependencies:
      - build:clang-3.9
    script:
      - ./tools/ci/simpleTest.sh


test:gcc-6:
    stage: test
    dependencies:
      - build:gcc-6
    script:
      - ./tools/ci/test.sh
    artifacts:
      paths:
        - build/out-coverage

documentation:
     stage: documentation
     script:
       - ./tools/ci/doxygen.sh
     artifacts:
       paths:
        - docs/html
